version: '3'

services:
  # 消息队列
  # rabbitmq:
  #   image: rabbitmq:3
  #   ports:
  #     - "5672:5672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: smsforwarder
  #     RABBITMQ_DEFAULT_PASS: smsforwarder
  #     RABBITMQ_DEFAULT_VHOST: smsforwarder
  #   networks:
  #     - smsforwarder-network

  # 后端服务
  backend:
    image: donjohnson630/smsforwarder-webx:backend-with-ui-latest
    # build:
    #   context: ./be
    #   dockerfile: Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - "smsforwarder=backend-with-ui"
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "80:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=smsforwarder
      - RABBITMQ_PASS=smsforwarder
      - RABBITMQ_VHOST=smsforwarder
      - SIMPLE_MODE=True
      - TIMEZONE=Asia/Shanghai
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/data/smsforwarder.db
      - DB_URI=sqlite:////app/data/smsforwarder.db
      - ADMIN_USERNAME=admin
      - DEBUG=True  # 启用简单模式，不依赖消息队列
    volumes:
      - ./data:/app/data
    networks:
      - smsforwarder-network

  # 前端服务
  # frontend:
  #   image: donjohnson630/smsforwarder-webx:frontend-latest
  #   build:
  #     context: ./fe
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - REACT_APP_BACKEND_URL=http://backend:8000
  #   networks:
  #     - smsforwarder-network

networks:
  smsforwarder-network:
    driver: bridge
