name: 构建并推送 Docker 镜像

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发，例如 v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: 登录到 Docker Hub
        uses: docker/login-action@v2
        with:
          username: donjohnson630
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 提取元数据（标签、标签等）
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: donjohnson630/smsforwarder-webx
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha
      
      - name: 构建并推送后端镜像
        uses: docker/build-push-action@v4
        with:
          context: ./be
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            donjohnson630/smsforwarder-webx:backend-${{ steps.meta.outputs.version }}
            donjohnson630/smsforwarder-webx:backend-latest
          cache-from: type=registry,ref=donjohnson630/smsforwarder-webx:backend-buildcache
          cache-to: type=registry,ref=donjohnson630/smsforwarder-webx:backend-buildcache,mode=max
      
      - name: 构建并推送前端镜像
        uses: docker/build-push-action@v4
        with:
          context: ./fe
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            donjohnson630/smsforwarder-webx:frontend-${{ steps.meta.outputs.version }}
            donjohnson630/smsforwarder-webx:frontend-latest
          cache-from: type=registry,ref=donjohnson630/smsforwarder-webx:frontend-buildcache
          cache-to: type=registry,ref=donjohnson630/smsforwarder-webx:frontend-buildcache,mode=max
      
      - name: 构建并推送完整镜像（包含标签信息）
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=donjohnson630/smsforwarder-webx:buildcache
          cache-to: type=registry,ref=donjohnson630/smsforwarder-webx:buildcache,mode=max
